[theme]
base = "light"
primaryColor = "#011E4B"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0E1A2B"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
